name: Secure AWS Terraform Pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

  
jobs:
  terraform-checks-plan:
    uses: ./.github/workflows/reusable-terraform-checks-plan.yml

  kics-scan:
    needs: terraform-checks-plan
    uses: ./.github/workflows/reusable-kics-scan.yml

  terraform-apply:
    needs: kics-scan
    uses: ./.github/workflows/reusable-terraform-apply.yml
