name: Reusable Terraform Checks and Plan

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-checks-plan:
    name: Terraform Checks and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive ../../

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::390403879329:role/GitHubActionsTerraformRole
          role-session-name: github-actions-terraform-checks

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infrastructure/environments/dev/tfplan
