name: Reusable Terraform Apply

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment:
      name: production

    defaults:
      run:
        working-directory: infrastructure/environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::390403879329:role/GitHubActionsTerraformRole
          role-session-name: github-actions-terraform-apply

      - name: Terraform init
        run: terraform init

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infrastructure/environments/dev

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
