name: Reusable Terraform Apply

on:
  workflow_call:

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment:
      name: production

    defaults:
      run:
        working-directory: infrastructure/environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform init
        run: terraform init

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infrastructure/environments/dev

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
